/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FundingRecipient: {
      address: "0xf7cd8fa9b94db2aa972023b379c7f72c65e4de9d",
      abi: [
        {
          type: "function",
          name: "complete",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "completed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 34,
    },
    CrowdFund: {
      address: "0x12975173b87f7595ee45dffb2ab812ece596bf84",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "fundingRecipientAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "balances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "contribute",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "deadline",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fundingRecipient",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract FundingRecipient",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "openToWithdraw",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "threshold",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "timeLeft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Contribution",
          inputs: [
            {
              name: "",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOpenToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "TooEarly",
          inputs: [
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "WithdrawTransferFailed",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 35,
    },
  },
  11155111: {
    FundingRecipient: {
      address: "0xbd6a7245cbc83572be75ce3c148f140f02dabd29",
      abi: [
        {
          type: "function",
          name: "complete",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "completed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10955475,
    },
    CrowdFund: {
      address: "0x223f34e3738218e71a7256a675b64cf7dbe77a8d",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "fundingRecipientAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "balances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "contribute",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "deadline",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fundingRecipient",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract FundingRecipient",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "openToWithdraw",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "threshold",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "timeLeft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Contribution",
          inputs: [
            {
              name: "",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "NotOpenToWithdraw",
          inputs: [],
        },
        {
          type: "error",
          name: "TooEarly",
          inputs: [
            {
              name: "deadline",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentTimestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "WithdrawTransferFailed",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10955475,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
